import { existsSync, unlinkSync } from "node:fs"
import { resolve } from "node:path"

// Builds the legacy published entry aliases (dist/index.js, dist/pi-extension.js,
// dist/dsh-plugin.js) as re-export stubs over the canonical dist/entries modules.
//
// The purge below exists because tsc never cleans its outDir: a tree built from
// the OLD flat layout still carries dist/<alias>.d.ts and its sourcemaps, and
// package.json's "files": ["dist"] would publish those broken legacy
// declarations beside the stubs. They are removed, never rewritten.

// Project root = scripts/.. (this script lives in scripts/)
const projectRoot = import.meta.dir ? resolve(import.meta.dir, "..") : process.cwd()

// The legacy published entry paths and the canonical modules they re-export.
const legacyAliases = [
  { alias: "index", entry: "opencode" },
  { alias: "pi-extension", entry: "pi" },
  { alias: "dsh-plugin", entry: "dsh" },
]

// A dangling alias must never be publishable: check every canonical module
// before writing anything, and fail loudly when one is missing.
const missing = legacyAliases
  .map(({ entry }) => resolve(projectRoot, "dist", "entries", `${entry}.js`))
  .filter((path) => !existsSync(path))
if (missing.length > 0) {
  console.error(`build:entry-aliases — missing canonical entry build output: ${missing.join(", ")}`)
  console.error("build:entry-aliases — run tsc first; refused to write a legacy alias that would dangle")
  process.exit(1)
}

// tsc emits a legacy declaration only while the flat src/<alias>.ts exists, and
// nothing removes it once that source is gone. Unlink exactly the declaration
// and sourcemap siblings — never the ".js" stub written below, and nothing under
// dist/entries/ — so a rebuilt tree cannot publish a stale .d.ts. The existsSync
// guard keeps a missing file a silent no-op, so the run stays idempotent.
const purged: string[] = []
for (const { alias } of legacyAliases) {
  for (const suffix of [".d.ts", ".d.ts.map", ".js.map"]) {
    const stale = resolve(projectRoot, "dist", `${alias}${suffix}`)
    if (existsSync(stale)) {
      unlinkSync(stale)
      purged.push(`dist/${alias}${suffix}`)
    }
  }
}

for (const { alias, entry } of legacyAliases) {
  // The alias must be a re-export stub, NOT a byte copy: the relative
  // specifiers emitted inside dist/entries/<entry>.js are one level deeper
  // ("../platform/..." instead of "./platform/..."), so a copied file would
  // resolve every import against the wrong directory.
  const stub = [
    `// Generated by scripts/build-entry-aliases.ts — do not edit by hand.`,
    `// Legacy entry alias. This is a re-export stub, not a byte copy: the emitted`,
    `// relative specifiers inside dist/entries/${entry}.js are one level deeper`,
    `// ("../platform/..." instead of "./platform/..."), so a copied file would`,
    `// resolve its imports against the wrong directory.`,
    `// Both lines are required: "export *" does not forward a default export.`,
    `export * from "./entries/${entry}.js"`,
    `export { default } from "./entries/${entry}.js"`,
    ``,
  ].join("\n")
  await Bun.write(resolve(projectRoot, "dist", `${alias}.js`), stub)
}

if (purged.length > 0) {
  console.log(`build:entry-aliases — purged ${purged.length} stale legacy declaration artifacts: ${purged.join(", ")}`)
}
console.log(
  `build:entry-aliases — wrote ${legacyAliases.length} legacy aliases: ${legacyAliases.map(({ alias }) => `dist/${alias}.js`).join(", ")}`,
)
process.exit(0)
