import { existsSync } from "node:fs"
import { resolve } from "node:path"

// Project root = scripts/.. (this script lives in scripts/)
const projectRoot = import.meta.dir ? resolve(import.meta.dir, "..") : process.cwd()

// The legacy published entry paths and the canonical modules they re-export.
const legacyAliases = [
  { alias: "index", entry: "opencode" },
  { alias: "pi-extension", entry: "pi" },
  { alias: "dsh-plugin", entry: "dsh" },
]

// A dangling alias must never be publishable: check every canonical module
// before writing anything, and fail loudly when one is missing.
const missing = legacyAliases
  .map(({ entry }) => resolve(projectRoot, "dist", "entries", `${entry}.js`))
  .filter((path) => !existsSync(path))
if (missing.length > 0) {
  console.error(`build:entry-aliases — missing canonical entry build output: ${missing.join(", ")}`)
  console.error("build:entry-aliases — run tsc first; refused to write a legacy alias that would dangle")
  process.exit(1)
}

for (const { alias, entry } of legacyAliases) {
  // The alias must be a re-export stub, NOT a byte copy: the relative
  // specifiers emitted inside dist/entries/<entry>.js are one level deeper
  // ("../platform/..." instead of "./platform/..."), so a copied file would
  // resolve every import against the wrong directory.
  const stub = [
    `// Generated by scripts/build-entry-aliases.ts — do not edit by hand.`,
    `// Legacy entry alias. This is a re-export stub, not a byte copy: the emitted`,
    `// relative specifiers inside dist/entries/${entry}.js are one level deeper`,
    `// ("../platform/..." instead of "./platform/..."), so a copied file would`,
    `// resolve its imports against the wrong directory.`,
    `// Both lines are required: "export *" does not forward a default export.`,
    `export * from "./entries/${entry}.js"`,
    `export { default } from "./entries/${entry}.js"`,
    ``,
  ].join("\n")
  await Bun.write(resolve(projectRoot, "dist", `${alias}.js`), stub)
}

console.log(
  `build:entry-aliases — wrote ${legacyAliases.length} legacy aliases: ${legacyAliases.map(({ alias }) => `dist/${alias}.js`).join(", ")}`,
)
process.exit(0)
