/**
 * Signal-type vocabulary — single source of truth.
 *
 * The 8-signal vocabulary and its category sets (terminating / pausing /
 * handoff / info) live here exactly once. Every consumer imports from
 * this module so the vocabulary is never duplicated.
 *
 * The type order is canonical — src/signal/signal-tool.ts derives its runtime
 * Zod enum from this array (`z.enum(SIGNAL_TYPES)`), so the validation
 * boundary can never drift from the vocabulary.
 */

/** The 8 valid signal types, in Zod-enum order. */
export const SIGNAL_TYPES = [
  "answer",
  "need_approval",
  "blocked",
  "need_clarification",
  "handoff",
  "progress",
  "revise_needed",
  "escalate",
] as const;

/** Union of the 8 valid signal types. */
export type SignalType = (typeof SIGNAL_TYPES)[number];

/**
 * Named signal type constants for ergonomic use (e.g. `SIGNAL_TYPE.ANSWER`).
 *
 * Type-bound to the SIGNAL_TYPES tuple via
 * `Record<Uppercase<SignalType>, SignalType>`: the compiler requires one key
 * per signal type (exhaustiveness) and rejects any key or value that is not
 * a valid signal type, so this object cannot drift from the vocabulary.
 */
export const SIGNAL_TYPE: Record<Uppercase<SignalType>, SignalType> = {
  ANSWER: "answer",
  NEED_APPROVAL: "need_approval",
  BLOCKED: "blocked",
  NEED_CLARIFICATION: "need_clarification",
  HANDOFF: "handoff",
  PROGRESS: "progress",
  REVISE_NEEDED: "revise_needed",
  ESCALATE: "escalate",
};

/** Signals that satisfy `continue_until` — terminate the node's run. */
export const TERMINATING_SIGNALS = new Set<string>(["answer", "revise_needed", "escalate"]);

/** Signals that trigger a pausing transition (approval / blocked / clarification). */
export const PAUSING_SIGNALS = new Set<string>(["need_approval", "blocked", "need_clarification"]);

/** Signals that route work elsewhere without terminating. */
export const HANDOFF_SIGNALS = new Set<string>(["handoff"]);

/** Informational signals with no state transition. */
export const INFO_SIGNALS = new Set<string>(["progress"]);

/** All 8 signal types — union of the four categories above. */
export const ALL_SIGNAL_TYPES = new Set<string>([
  ...TERMINATING_SIGNALS,
  ...PAUSING_SIGNALS,
  ...HANDOFF_SIGNALS,
  ...INFO_SIGNALS,
]);

/**
 * Terminating signals in descending severity order.
 *
 * Used by the completion evaluator so the highest-severity terminating signal
 * wins when multiple were recorded during a sub-agent session.
 */
export const TERMINATING_SIGNALS_BY_SEVERITY = ["escalate", "revise_needed", "answer"] as const;

/**
 * Synthetic terminating signal emitted by the completion evaluator for a
 * normally-completed task whose sub-agent never called `signal()`.
 *
 * A task that finished clean without an explicit `signal()` call IS a clean
 * `answer` — the plugin auto-emits on the sub-agent's behalf. The
 * `__inferred` marker is retained purely for observability so downstream
 * consumers know this signal was generated by the framework, not the
 * sub-agent.
 *
 * Shared constant — used by the completion evaluator (populate
 * `task.terminatingSignal`) and available to engine code for signal
 * classification.
 */
export const SYNTHETIC_ANSWER_SIGNAL = {
  type: "answer" as const,
  payload: { __inferred: true } as const,
} as const;
